version: '3.7'

services:
  amarillo:
    image: ${DOCKER_IMAGE:?missing env var DOCKER_IMAGE}:${DOCKER_TAG:?missing env var DOCKER_TAG}
    networks:
      - public
    environment:
      - RIDE2GO_TOKEN=${RIDE2GO_TOKEN:?missing env var RIDE2GO_TOKEN}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == node-001.tpwd-bb-navi
      labels:
        traefik.docker.network: public
        traefik.enable: "true"
        traefik.frontend.rule: Host:amarillo.bbnavi.de
        traefik.frontend.passHostHeader: "true"
        traefik.port: '8000'

networks:
  public:
    external: true
