# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: realtime_extension.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import gtfs_realtime_pb2 as gtfs__realtime__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='realtime_extension.proto',
  package='transit_realtime',
  syntax='proto2',
  serialized_options=b'\n\007de.mfdz',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18realtime_extension.proto\x12\x10transit_realtime\x1a\x13gtfs-realtime.proto\"/\n\x1bMfdzTripDescriptorExtension\x12\x10\n\x08trip_url\x18\x01 \x01(\t:i\n\x0ftrip_descriptor\x12 .transit_realtime.TripDescriptor\x18\xa8\x46 \x01(\x0b\x32-.transit_realtime.MfdzTripDescriptorExtensionB\t\n\x07\x64\x65.mfdz'
  ,
  dependencies=[gtfs__realtime__pb2.DESCRIPTOR,])


TRIP_DESCRIPTOR_FIELD_NUMBER = 9000
trip_descriptor = _descriptor.FieldDescriptor(
  name='trip_descriptor', full_name='transit_realtime.trip_descriptor', index=0,
  number=9000, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)


_MFDZTRIPDESCRIPTOREXTENSION = _descriptor.Descriptor(
  name='MfdzTripDescriptorExtension',
  full_name='transit_realtime.MfdzTripDescriptorExtension',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='trip_url', full_name='transit_realtime.MfdzTripDescriptorExtension.trip_url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=114,
)

DESCRIPTOR.message_types_by_name['MfdzTripDescriptorExtension'] = _MFDZTRIPDESCRIPTOREXTENSION
DESCRIPTOR.extensions_by_name['trip_descriptor'] = trip_descriptor
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MfdzTripDescriptorExtension = _reflection.GeneratedProtocolMessageType('MfdzTripDescriptorExtension', (_message.Message,), {
  'DESCRIPTOR' : _MFDZTRIPDESCRIPTOREXTENSION,
  '__module__' : 'realtime_extension_pb2'
  # @@protoc_insertion_point(class_scope:transit_realtime.MfdzTripDescriptorExtension)
  })
_sym_db.RegisterMessage(MfdzTripDescriptorExtension)

trip_descriptor.message_type = _MFDZTRIPDESCRIPTOREXTENSION
gtfs__realtime__pb2.TripDescriptor.RegisterExtension(trip_descriptor)

DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
