name: Docker Image CI

on:
  push:
    branches: [ deploy ]
  pull_request:
    branches: [ deploy ]

jobs:
  prep:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    # env:
    #  RIDE2GO_TOKEN: ${{ secrets.RIDE2GO_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        registry: registry.gitlab.tpwd.de
        username: ${{ secrets.GITLAB_USERNAME }}
        password: ${{ secrets.GITLAB_PASSWORD }}
    - id: docker_build
      uses: docker/build-push-action@v2
      with:
        cache-from: |
          type=registry,ref=registry.gitlab.tpwd.de/tpwd/bb-navi/amarillo
        push: true
        tags: registry.gitlab.tpwd.de/tpwd/bb-navi/amarillo:production
        #secrets: |
        #  "RIDE2GO_TOKEN=${{ secrets.RIDE2GO_TOKEN }}"
  deploy:
    runs-on: ubuntu-latest
    needs:
      - prep
    container: r.planetary-quantum.com/quantum-public/cli:2
    env:
      QUANTUM_USER: ${{ secrets.QUANTUM_USER }}
      QUANTUM_PASSWORD: ${{ secrets.QUANTUM_PASSWORD }}
      QUANTUM_ENDPOINT: "tpwd-bb-navi"
      QUANTUM_STACK: "amarillo-tpwd-bb-navi"
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Planetary Quantum
        run: quantum-cli stacks update --create --wait
